[package]
name = "search-content-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
log = "0.4.20"
tokio = "1.29.1"
