version: '3'

services:
  cache:
    image: redis
    container_name: redis_server
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - $PWD/.data/redis-data:/var/redis/data
      - $PWD/.data/redis.conf:/usr/local/etc/redis/redis.conf
